spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/loan_db
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: loan-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
resilience4j:
  circuitbreaker:
    instances:
      documentService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:  health, metrics, circuitbreakerevents

  endpoint:
    health:
      show-details: always

#  retry:
#    instances:
#      documentService:
#        max-attempts: 3
#        wait-duration: 1s

server:
  port: 4002

logging:
  level:
    org.springframework.kafka: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registery: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:4005/eureka