spring:
  kafka:
    bootstrap-servers: localhost:9092

#    consumer:
#      group-id: loan-stage-history-group
#      auto-offset-reset: earliest
#
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#
#      properties:
#        spring.json.trusted.packages: "com.example.loanapplication.loan_service.kafka.events"
#        spring.json.value.default.type: com.example.loanapplication.loan_service.kafka.events.LoanStageHistoryEvent
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/loan_db
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: loan-service
server:
  port: '4002'

logging:
  level:
    org.springframework.kafka: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registery: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:4005/eureka