
server:
  port: 4006

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: AUTH-USER-SERVICE
          uri:  lb://AUTH-USER-SERVICE
          predicates:
            -Paths: /api/auth/**

        - id: DOCUMENT-SERVICE
          uri: lb://DOCUMENT-SERVICE
          predicates:
            -Paths: /api/documents/**

        - id: RCU-SERVICE
          uri: lb://RCU-SERVICE
          predicates:
            -Paths: /api/rcu/**

        - id: LOAN-SERVICE
          uri: lb://LOAN-SERVICE
          predicates:
            -Paths: /api/loans/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:4005/eureka