server:
  port: 4006

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: AUTH-USER-SERVICE
              uri: lb://AUTH-USER-SERVICE
              predicates:
                - Path=/api/auth/**,/api/users/**

            - id: DOCUMENT-SERVICE
              uri: lb://DOCUMENT-SERVICE
              predicates:
                - Path=/api/documents/**

            - id: RCU-SERVICE
              uri: lb://RCU-SERVICE
              predicates:
                - Path=/api/rcu/**

            - id: LOAN-SERVICE
              uri: lb://LOAN-SERVICE
              predicates:
                - Path=/api/loans/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:4005/eureka