spring:
  application:
    name: rcu-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: rcu_db
      uuid-representation: standard

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

#We gave common config for all CBs here we can change based on our Read/Write traffic rate
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

    instances:
      DocumentServicegetAllDocumentsByLoanIdUUID:
        base-config: default

      DocumentServicegetAllDocumentsByApplicantIdUUID:
        base-config: default

      DocumentServicegetDocumentByIdUUID:
        base-config: default

      DocumentServicedeleteAllDocumentsByLoanIdString:
        base-config: default

      DocumentServicedeleteAllDocumentsByApplicantIdString:
        base-config: default

      DocumentServiceupdateDocumentStatusString:
        base-config: default

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always

server:
  port: 4004

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:4005/eureka